apiVersion: v1
kind: Service
metadata:
 name: mysite
 labels:
   name: mysite
spec:
 type: LoadBalancer
 ports:
   - port: 80
     targetPort: http-server
     protocol: TCP
 selector:
   name: mysite 
